### ISSUE TITLE
When I hit tab is erlang suppose to autocomplete

### ISSUE THREAD

**Issue by chrisjluc** [vim-erlang/vim-erlang-omnicomplete#20]
I tried the example in the documentation where I typed `list_to` and hit tab but then nothing happens. The documentation says hit `|i_CTRL-X_CTRL-O|` but I'm not sure what that means, I tried playing around with CTRL-X, CTRL-O, CTRL-P, CTRL-I, but no autocomplete occurs or was offered.

I installed using pathogen instructions and I'm able to search up the `:help vim-erlang-omnicomplete` I'm not sure if the installation didn't occur correctly.

**Comment by sanmiguel** [comment]
Hi there! In vim help parlance, `i_CTRL-X_CTRL-O` means `while in insert mode, press Ctrl-X then Ctrl-O`.

If configured correctly you should see a menu appear at the cursor with available completions. This might take a second to show.

If that's not working, check that the omnifunc is set correctly by running `:set omnifunc` - it should print `omnifunc=erlang_complete#Complete`

Let us know what you find...

**Comment by chrisjluc** [comment]
Thanks! It works now! Is there a way to have the autocomplete suggestions without hitting Ctrl-X then Ctrl-O? Like hitting tab?

**Comment by sanmiguel** [comment]
You're welcome - glad we were able to get you going with it!

There are a few plugins out there for that kind of thing. [Supertab](https://github.com/ervandew/supertab) is probably one of the best known. Personally I tried it years back and ended up getting used to using `CTRL-X_CTRL-O`. There are a number of other useful completion types under the `CTRL-X` command - see `:help ins-completion` for the full details but here's the overview from that page:

```
1. Whole lines						|i_CTRL-X_CTRL-L|
2. keywords in the current file				|i_CTRL-X_CTRL-N|
3. keywords in 'dictionary'				|i_CTRL-X_CTRL-K|
4. keywords in 'thesaurus', thesaurus-style		|i_CTRL-X_CTRL-T|
5. keywords in the current and included files		|i_CTRL-X_CTRL-I|
6. tags							|i_CTRL-X_CTRL-]|
7. file names						|i_CTRL-X_CTRL-F|
8. definitions or macros				|i_CTRL-X_CTRL-D|
9. Vim command-line					|i_CTRL-X_CTRL-V|
10. User defined completion				|i_CTRL-X_CTRL-U|
11. omni completion					|i_CTRL-X_CTRL-O|
12. Spelling suggestions				|i_CTRL-X_s|
```

I'll close this issue now as you've got it working - if you have any more questions feel free to re-open it, or you can also reach us in #vim-erlang on freenode.
