### ISSUE TITLE
Completion in Cygwin environment is broken

### ISSUE THREAD

**Issue by ravindersingh17** [vim-erlang/vim-erlang-omnicomplete#21]
Trying to use omnicomplete for erlang in Cygwin results in the following error being generated:

escript: Failed to open file: /home/ravinder/.vim/bundle/vim-erlang-omnicomplete/autoload/erlang_complete.erl^M f

**Comment by ravindersingh17** [comment]
To fix this there needs to be a wrapper for filepath given to escript so that it is converted to the correct windows path.

**Comment by ravindersingh17** [comment]
I have a fix to this. Attached is a patch.
[patch.txt](https://github.com/vim-erlang/vim-erlang-omnicomplete/files/1466671/patch.txt)

**Comment by hcs42** [comment]
@ravindersingh17 Thank you for the patch.

I modified it a bit and pushed the modified version to this branch: https://github.com/hcs42/vim-erlang-omnicomplete/tree/cygwin Could you check if it still works?

**Comment by hcs42** [comment]
I pushed my fix to master.
