### ISSUE TITLE
Any deoplete implementation? 

### ISSUE THREAD

**Issue by ggerico** [vim-erlang/vim-erlang-omnicomplete#23]
I know ... but could you make vim-erlang-omnicomplete compatible with the deoplete plugin?
It works like a charm with the alchemist.vim plugin for elixir and a dozen of others languages! 

Tks!

**Comment by hcs42** [comment]
I don't use Neovim, so I won't implement support for Neovim features/plugins myself. But if I receive a PR, I can test it and merge it if it works.

**Comment by wsdjeg** [comment]
deoplete support vim8 now, and deoplete has omni source.

**Comment by shymega** [comment]
@wsdjeg Not entirely sure what you mean by that, but I can confirm that deoplete (I'm running it on neovim) does *have* this plugin as a source, which is good, for sure. However, its just getting deoplete to automatically suggest completions, as I currently have to use C-x C-o. Other languages do not appear to have this limitation.
