### ISSUE TITLE
Escript Error When Attempting to OmniComplete Functions from the "string" Module

### ISSUE THREAD

**Issue by Hypro999** [vim-erlang/vim-erlang-omnicomplete#27]
![string](https://user-images.githubusercontent.com/29123352/90864626-a3ca9a00-e3ae-11ea-8a18-8a7275f392de.png)

I'm still relatively new to Erlang, so I'm not _exactly_ sure what the cause of this error is. However, what I *can* see is that it's something about an unsatisfied/unmatched case. I haven't seen this issue with any other module so far.

**Comment by hcs42** [comment]
I installed Erlang 23.0 and managed to reproduce the issue. I will look into it.

**Comment by Hypro999** [comment]
Awesome, thank you so much @hcs42!

**Comment by hcs42** [comment]
@Hypro999 I implemented a fix in my [fix_otp_23 branch](https://github.com/hcs42/vim-erlang-omnicomplete/commits/fix_otp_23). (See the explanation in the commit message of the "Fix multiple type spec clauses with OTP 23" commit.)

 Would you try it?

**Comment by Hypro999** [comment]
@hcs42 - Just tried it out and the problem seems to have been fixed! The commit message was very helpful for understanding what went wrong. Thanks for working on this!

**Comment by Hypro999** [comment]
So, can we get this merged into master?

**Comment by hcs42** [comment]
I pushed the fix into master.
