### ISSUE TITLE
Infinite recursion process_rebar_configs function in windows msys2 shell

### ISSUE THREAD

**Issue by brainstormi** [vim-erlang/vim-erlang-omnicomplete#5]
When using msys2 shell to work with vim-erlang-omnicomplete it causes and infinite recursion exhausting machine resources when trying to look for rebar configs files.
The issue seems to be related due to the recursion fo find file configs ends when reaching root directory ("/"):
```
     case {Res, AbsDir} of
        {error, _} ->
            error;
        {_, "/"} ->
            ok;
        {_, _} ->
            process_rebar_configs(filename:dirname(AbsDir))
```
In Windows, Erlang automatically translates filesystem path formats from "/C/foo/bar" passed as base-dir parameter to erlang_complete.erl escript to "C:/foo/bar", never mathing the {_, "/"} -> clausule when reaching "C:/" root directory while transversing the tree.

**Comment by hcs42** [comment]
Could you check what `filename:dirname("/C")` and `filename:dirname("C:/")` return on Windows?

(Similar issue in vim-erlang-compiler: https://github.com/vim-erlang/vim-erlang-compiler/issues/18.)

**Comment by brainstormi** [comment]
```
1>  filename:dirname("C:/").
"C:/"
2> filename:dirname("/C").
"/"
```
The issue with the second option is that Erlang internally automatically translates /C/foo/bar paths to C:/foo/bar

**Comment by hcs42** [comment]
> The issue with the second option is that Erlang internally automatically translates /C/foo/bar paths to C:/foo/bar

So this means that the Erlang code in vim-erlang needs to handle only the "drive:/" case, but not the "/drive" case?

**Comment by brainstormi** [comment]
Exactly, quick tests changing erlang_complete.erl show that "drive:/" matchs succesfully in windows to stops the infinitive recursion in process_rebar_configs

**Comment by hcs42** [comment]
Ok, I fixed it on my branch: https://github.com/hcs42/vim-erlang-omnicomplete/commits/fix_windows_recursion

Could you test it? If it works, I will create a similar branch for vim-erlang-compiler.

**Comment by brainstormi** [comment]
Excuse me, I missed to the track of this. I tested it and works perfectly.

**Comment by hcs42** [comment]
No worries, better late the never :) I merged it: https://github.com/vim-erlang/vim-erlang-omnicomplete/pull/6

I will make the corresponding PR for vim-erlang-compiler in a week.
