### ISSUE TITLE
Youcompleteme completion disappears after entering anything after :

### ISSUE THREAD

**Issue by nlsun** [vim-erlang/vim-erlang-omnicomplete#8]
https://github.com/Valloric/YouCompleteMe/issues/862

"YCM expects the omnifunc to adhere to the behavior described by :h complete-functions in Vim. That's about it. It might be that vimerl's omnifunc is expecting to be called on every keystroke; if it is, it shouldn't be doing that."

**Comment by hcs42** [comment]
I found one thing that might be the culprit. I fixed it in my [youcompleteme_fix branch][2]. Could you try it?

If it doesn't work, please also try my [dbg branch][3], which logs the parameters and the return value of the completion function. You can view the log with the `:messages` command.

**Background:** In Vim, there are two kinds of completion functions:

1. User defined completion (`:h compl-function`) is specified by the `'completefunc'` option, and can be triggered by hitting `i_CTRL-X_CTRL-U`.
2. Omni completion (`:h compl-omni`) is specified by the `'omnifunc'` option, and can be triggered by hitting `i_CTRL-X_CTRL-O`.

Although `:h complete-functions` handles them the same way, `completefunc` functions can use the `complete_add()` function  to add elements to the completion list besides returning those elements, which is not allowed in `omnifunc` functions (`:h complete_add()`):

    complete_add({expr})                            *complete_add()*
        Add {expr} to the list of matches.  Only to be used by the
        function specified with the 'completefunc' option.
        Returns 0 for failure (empty string or out of memory),
        1 when the match was added, 2 when the match was already in
        the list.
        See |complete-functions| for an explanation of {expr}.  It is
        the same as one item in the list that 'omnifunc' would return.

The problem with vim-erlang-omnicomplete might be that its omnifunc doesn't return the matches, instead it calls the complete_add() function. So the patch modifies vim-erlang-omnicomplete to return the matches directly.

[2]: https://github.com/hcs42/vim-erlang-omnicomplete/commits/youcompleteme_fix
[3]: https://github.com/hcs42/vim-erlang-omnicomplete/commits/dbg

**Comment by GoNZooo** [comment]
I just pulled the youcompleteme_fix branch and can confirm that this works without using the fix mentioned in https://github.com/Valloric/YouCompleteMe/issues/862 which was to put the following in vimrc:

    let g:ycm_cache_omnifunc = 0

It does indeed seem that this branch fixes how vim-erlang-omnicomplete presents the available completions and should make it play nicely with YCM.

**Comment by nlsun** [comment]
@hcs42 It seems to have fixed it for me as well, exactly like @GoNZooo said.

Sorry for the late response, if you were waiting for my affirmation as well.

**Comment by hcs42** [comment]
@GoNZooo @nlsun: Thank you both for testing (and reporting), I merged the fix: https://github.com/vim-erlang/vim-erlang-omnicomplete/pull/9
